apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  namespace: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: nginx
        imagePullPolicy: IfNotPresent
        image: proxy-local
        
        ports:
        - containerPort: 443

---

apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: webapp
spec:
  selector:
    app: proxy
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30433
  type: NodePort

---